-   id: {id}
    name: {id}
    entry: '{entry}:{version}'
    language: {language}
    '{match_key}': {match_val}
    args: {args}
    require_serial: {require_serial}
    additional_dependencies: {additional_dependencies}
