-   id: {entry}
    name: {name}
    entry: {entry}
    language: {language}
    '{match_key}': {match_val}
    args: {args}
    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['{name}@{version}']
    minimum_pre_commit_version: 0.7.0
